spring:
  datasource:
    url: jdbc:mysql://mysql1:3306/mysql?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 111111
