version: '3'
services:
  mysql1:
    image: mysql:8.0.22
    container_name: mysql1
    restart: always
    volumes:
      - $PWD/data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: "111111"
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai
    command: --default-authentication-plugin=mysql_native_password
    user: root
    networks:
      - micro
  mvc-app:
    build:
      context: ../java
      dockerfile: ./Dockerfile
    environment:
      TZ: Asia/Shanghai
    ports:
      - 8080:8080
    volumes:
      - $PWD/log:/app/logs
    depends_on:
      - mysql1
    networks:
      - micro

networks:
  micro:
    driver: bridge

